#!/usr/bin/env bash
# This script prints numbers 1 to 20 and displays special bad luck messages for 4, 9, and 17
count=1
while [ "$count" -le 20 ]
do
    echo "$count"
    case "$count" in
            echo "bad luck from China"
            echo "bad luck from Japan"
            echo "bad luck from Italy"
    count=$((count + 1))
done
